FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*
    
# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Make src importable
ENV PYTHONPATH=/app/src

EXPOSE 8000

# Run with Python + Uvicorn
CMD ["python", "-m", "uvicorn", "stockmarketanalytics.main:app", "--host", "0.0.0.0", "--port", "8000"]