"""Add auth and rate limiter

Revision ID: 8396bc5c59bd
Revises: 82086baae6e9
Create Date: 2026-09-04 14:35:38.009163

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8396bc5c59bd"
down_revision: str | Sequence[str] | None = "82086baae6e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("1"), "option_calculations", type_="foreignkey")
    op.create_foreign_key(None, "option_calculations", "stocks", ["stock_id"], ["id"])
    op.create_index(
        op.f("ix_stock_prices_stock_id"), "stock_prices", ["stock_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_prices_trading_date"),
        "stock_prices",
        ["trading_date"],
        unique=False,
    )
    op.create_index(op.f("ix_stocks_symbol"), "stocks", ["symbol"], unique=True)
    op.drop_constraint(op.f("1"), "trading_analyses", type_="foreignkey")
    op.create_foreign_key(None, "trading_analyses", "stocks", ["stock_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trading_analyses", type_="foreignkey")
    op.create_foreign_key(
        op.f("1"),
        "trading_analyses",
        "stocks",
        ["stock_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_stocks_symbol"), table_name="stocks")
    op.drop_index(op.f("ix_stock_prices_trading_date"), table_name="stock_prices")
    op.drop_index(op.f("ix_stock_prices_stock_id"), table_name="stock_prices")
    op.drop_constraint(None, "option_calculations", type_="foreignkey")
    op.create_foreign_key(
        op.f("1"),
        "option_calculations",
        "stocks",
        ["stock_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
